index:
  path: /
  controller: App\Controller\HomeController::index
  methods: [GET]

#Room
room_list:
  path: /room
  controller: App\Controller\RoomController::list
  methods: [GET]

room_create:
  path: /room
  controller: App\Controller\RoomController::create
  methods: [POST]

room_show:
  path: /room/{id}
  controller: App\Controller\RoomController::show
  methods: [GET]

room_update:
  path: /room/{id}
  controller: App\Controller\RoomController::update
  methods: [PUT]

room_delete:
  path: /room/{id}
  controller: App\Controller\RoomController::delete
  methods: [DELETE]

#Guest
guest_list:
  path: /guest
  controller: App\Controller\GuestController::list
  methods: [GET]

guest_create:
  path: /guest
  controller: App\Controller\GuestController::create
  methods: [POST]

guest_show:
  path: /guest/{id}
  controller: App\Controller\GuestController::show
  methods: [GET]

guest_update:
  path: /guest/{id}
  controller: App\Controller\GuestController::update
  methods: [PUT]

guest_delete:
  path: /guest/{id}
  controller: App\Controller\GuestController::delete
  methods: [DELETE]

#Amount
amount_create:
  path: /amount
  controller: App\Controller\AmountController::create
  methods: [POST]

amount_update:
  path: /amount
  controller: App\Controller\AmountController::update
  methods: [PUT]

#Booking
booking_create:
  path: /booking
  controller: App\Controller\BookingController::create
  methods: [POST]

booking_list:
  path: /booking
  controller: App\Controller\BookingController::list
  methods: [GET]